module.exports = [
  {
    catalog: 'messier',
    code: 'm31',
    name: 'andromeda',
    size: '220000',
    type: 'spiral',
  },
  {
    catalog: 'ngc',
    code: '1',
    name: '',
    size: '220000',
    type: 'spiral',
  },
  {
    catalog: 'ngc',
    code: '2',
    name: 'andromeda',
    size: '220000',
    type: 'spiral',
  },
  {
    catalog: 'ngc',
    code: '3',
    name: '',
    size: '220000',
    type: 'lenticular',
  },
  {
    catalog: 'ngc',
    code: '4',
    name: '',
    size: '220000',
    type: 'lenticular',
  },
  {
    catalog: 'ngc',
    code: '5',
    name: '',
    size: '220000',
    type: 'elliptical',
  },
  {
    catalog: 'ngc',
    code: '6',
    name: '',
    size: '220000',
    type: 'lenticular',
  },
  {
    catalog: 'ngc',
    code: '7',
    name: '',
    size: '220000',
    type: 'spiral',
  },
]
